SmartGarage/SmartGarage.MVC/Models/CarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.MVC.Models
{
    public class CarViewModel
    {
        public int Id { get; set; }
        public string RegistrationPlate { get; set; } 
        public string VIN { get; set; } 
        public int CarModelId { get; set; }
        public string CarModelName { get; set; }
        public string ManufacturerName { get; set; }
        public int UserId { get; set; }

        public string UserName { get; set; }
    }
}

SmartGarage/SmartGarage.MVC/Controllers/CarController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartGarage.MVC.Mapper;
using SmartGarage.MVC.Models;
using SmartGarage.Services.Contracts;
using SmartGarage.Services.Exceptions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.MVC.Controllers
{
    [Authorize(Roles = "Employee")]
    public class CarController : Controller
    {
        private readonly IUserService userService;
        private readonly ICarService carService;
        private readonly ICarModelService carModelService;
        private readonly IManufacturerService manufacturerService;
        private readonly ViewModelMapper mapper;
        public CarController(IUserService userService, ICarService carService, 
                             ICarModelService carModelService, ViewModelMapper mapper, 
                             IManufacturerService manufacturerService)
        {
            this.userService = userService ?? throw new ArgumentNullException(nameof(userService)); ;
            this.carService = carService ?? throw new ArgumentNullException(nameof(carService));
            this.carModelService = carModelService ?? throw new ArgumentNullException(nameof(carModelService));
            this.manufacturerService = manufacturerService ?? throw new ArgumentNullException(nameof(manufacturerService));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        public async Task<IActionResult> Index(int userId)
        {

            var cars = await carService.GetAllCarsForUser(userId);
            var carsViewModel = cars.Select(c => mapper.CarDTOToVM(c)).ToList();

            foreach (var item in carsViewModel)
            {
                item.ManufacturerName = (await carModelService.GetCarModelAsync(item.CarModelId))?.Manufacturer?.Name;
            }

            var users = await userService.GetAllCustomersAsync();

            ViewData["UserId"] = new SelectList(users, "Id", "Email").ToList();

            
            return View(carsViewModel);
        }
        public async Task<IActionResult> Details([FromRoute] int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var car = await carService.GetCarAsync(Convert.ToInt32(id));
            
            if (car == null)
            {
                return NotFound();
            }

            var carViewModel = mapper.CarDTOToVM(car);

            return View(carViewModel);
        }

        public async Task<ActionResult> Create()
        {
            var customers = await userService.GetAllCustomersAsync();

            ViewData["UserId"] = new SelectList(customers, "Id", "Email").ToList();

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CarInputViewModel model)
        {
            try
            {
                var carDTO = mapper.CarInputVMToDTO(model);

                var userId = await userService.ValidateUserExist(model.UserId);

                var manufacturerId = await manufacturerService.CreateIfNotExistAsync(model.ManufacturerName);

                var carModelId = await carModelService.CreateCarModelIfNotExistAsync(model.CarModelName, manufacturerId);

                carDTO.UserId = userId;
                carDTO.CarModelId = carModelId;

                var newCar = await this.carService.CreateCarAsync(carDTO);

                return RedirectToAction(nameof(Index));
            }
            catch (ResourceAlreadyExistException e)
            {
                return Conflict(e.Message);
            }
            catch (InvalidParameterException e)
            {
                return BadRequest(e.Message);
            }
        }

        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        
        public async Task<IActionResult> Edit(int id, CarInputViewModel car)
        {
            try
            {
                var carDTO = mapper.CarInputVMToDTO(car);
                carDTO.Id = id;

                //var userId = await userService.ValidateUserExist(car.UserId);
                //carDTO.UserId = userId;

                var manufacturerId = await manufacturerService.CreateIfNotExistAsync(car.ManufacturerName);

                var carModelId = await carModelService.CreateCarModelIfNotExistAsync(car.CarModelName, manufacturerId);
                carDTO.CarModelId = carModelId;

                await this.carService.UpdateCarAsync(carDTO);

                return RedirectToAction(nameof(Index));
            }
            catch (ResourceNotExistException e)
            {
                return NotFound(e.Message);
            }
            catch (InvalidParameterException e)
            {
                return BadRequest(e.Message);
            }
        }
    }
}

SmartGarage/SmartGarage.MVC/Views/Car/Create.cshtml
@model CarInputViewModel

@{ ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h4>Add new car to our customer:</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Car">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control" />
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label>User</label>
                <select name="UserId" class="form-control" asp-items="@((List<SelectListItem>)ViewData["UserId"])"></select>
            </div>
            <div class="form-group">
                <label @*asp-for="ManufacturerName" class="control-label"*@>Manufacturer</label>
                <input asp-for="ManufacturerName" class="form-control" />
                <span asp-validation-for="ManufacturerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label @*asp-for="CarModelName" class="control-label"*@>Model</label>
                <input asp-for="CarModelName" class="form-control" />
                <span asp-validation-for="CarModelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VIN" class="control-label"></label>
                <input asp-for="VIN" class="form-control" />
                <span asp-validation-for="VIN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistrationPlate" class="control-label"></label>
                <input asp-for="RegistrationPlate" class="form-control" />
                <span asp-validation-for="RegistrationPlate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-secondary btn-sm" asp-action="Index"> Back to full list</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SmartGarage/SmartGarage.MVC/Views/Car/Details.cshtml
@model CarViewModel

@{ ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h1>Details</h1>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationPlate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RegistrationPlate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VIN)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VIN)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CarModelName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CarModelName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturerName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <div>
            <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
            <a asp-action="Index">Back to List</a>
        </div>

SmartGarage/SmartGarage.MVC/Views/Car/Edit.cshtml
@model CarInputViewModel

@{ ViewData["Title"] = "Edit"; }

<h1>Edit</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="RegistrationPlate" class="control-label"></label>
                <input asp-for="RegistrationPlate" class="form-control" />
                <span asp-validation-for="RegistrationPlate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VIN" class="control-label"></label>
                <input asp-for="VIN" class="form-control" />
                <span asp-validation-for="VIN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarModelName" class="control-label"></label>
                <input asp-for="CarModelName" class="form-control" />
                <span asp-validation-for="CarModelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturerName" class="control-label"></label>
                <input asp-for="ManufacturerName" class="form-control" />
                <span asp-validation-for="ManufacturerName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SmartGarage/SmartGarage.MVC/Views/Car/Index.cshtml
@model IEnumerable<CarViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Cars</h1>
<br />
<br />
<p>
    <a asp-action="Create" asp-controller="Car" class="btn btn-success">Create Car</a>
</p>
<br />

<form asp-area="" asp-controller="Car" asp-action="Index">
    <div class="form-group custom-size">

        <label>Customer</label>
        <select name="UserId" class="form-control" asp-items="@((List<SelectListItem>)ViewData["UserId"])"></select>

        <br />
        <input type="submit" value="Filter" role="button" class="btn btn-primary" />
    </div>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                Registration Plate
            </th>
            <th>
                Model
            </th>
            <th>
                Manufacturer
            </th>
            <th>
                Customer
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.RegistrationPlate
                </td>
                <td>
                    @item.CarModelName
                </td>
                <td>
                    @item.ManufacturerName
                </td>
                <td>
                    @item.UserName
                    
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class = "btn btn-outline-warning">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class = "btn btn-outline-dark">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>