SmartGarage/SmartGarage.MVC/Models/OperationViewModel.cs
using SmartGarage.Data.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.MVC.Models
{
    public class OperationViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double PriceValue { get; set; }
        public string PriceCurrency { get; set; }
    }
}

SmartGarage/SmartGarage.MVC/Controllers/OperationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SmartGarage.MVC.Mapper;
using SmartGarage.MVC.Models;
using SmartGarage.Services.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.MVC.Controllers
{
    public class OperationController : Controller
    {
        private readonly ViewModelMapper mapper;
        private readonly IOperationService operationService;

        public OperationController(IOperationService operationService, ViewModelMapper mapper)
        {
            this.operationService = operationService;
            this.mapper = mapper;
        }
        // GET: OperationController
        public async Task<ActionResult> Index(string name, int price)
        {
            var operationDTOs = await operationService.GetAllOperationsByNameAndPriceAsync(name, price);

            var operationVMs = operationDTOs.Select(o => mapper.OperationDTOToVM(o)).ToList();

            return View(operationVMs);
        }

        // GET: OperationController/Details/5
        public ActionResult Details(int id)
        {

            return View();
        }

        // GET: OperationController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: OperationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(OperationInputViewModel model)
        {
            try
            {
                var dto = mapper.OperationInputVMToDTO(model);

                await operationService.CreateAsync(dto);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OperationController/Edit/5
        public ActionResult Update(int id)
        {
            return View();
        }

        // POST: OperationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(int id, OperationInputViewModel model)
        {
            try
            {
                var operationDTO = mapper.OperationInputVMToDTO(model);
                operationDTO.Id = id;

                await operationService.UpdateAsync(operationDTO);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // POST: OperationController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                await operationService.DeleteAsync(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SmartGarage/SmartGarage.MVC/Views/Operation/Create.cshtml
@model OperationInputViewModel

@{ ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h4>Add new Service:</h4>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Operation">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriceValue" class="control-label"></label>
                <input asp-for="PriceValue" class="form-control" />
                <span asp-validation-for="PriceValue" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SmartGarage/SmartGarage.MVC/Views/Operation/Index.cshtml
@model IEnumerable<OperationViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Services</h1>
<br />
<br />

<p>
    <a asp-action="Create" asp-controller="Operation" class="btn btn-success">Create Service</a>
</p>
<br />

<form asp-area="" asp-controller="Operation" asp-action="Index">
    <div class="form-group custom-size">

        <label>Name</label>
        <input name="Name" type="text" class="form-control" id="Name">

        <label>Price</label>
        <input name="Price" type="text" class="form-control" id="Price">

        <br />
        <input type="submit" value="Filter" role="button" class="btn btn-primary" />
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Name
                </td>
                <td>
                    <p>
                        @item.PriceValue EUR
                    </p>
                </td>
                <td>
                    <a asp-action="Update" asp-controller="Operation" asp-route-id="@item.Id" class="btn btn-outline-warning">Edit</a> 
                    
                    <a asp-action="Delete" asp-controller="Operation" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to delete shipment : @item.Name')" value="Delete" class="btn btn-outline-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

SmartGarage/SmartGarage.MVC/Views/Operation/Update.cshtml
@model OperationInputViewModel

@{ ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h4>Edit Service:</h4>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" asp-controller="Operation">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="PriceValue" class="control-label"></label>
                <input asp-for="PriceValue" class="form-control" />
                <span asp-validation-for="PriceValue" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}