SmartGarage/SmartGarage.MVC/Models/VisitViewModel.cs
using SmartGarage.Services.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.MVC.Models
{
    public class VisitViewModel
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public int CarId { get; set; }
        public double TotalPrice { get; set; }
        public List<OperationDTO> Operations { get; set; }
    }
}

SmartGarage/SmartGarage.MVC/Controllers/VisitController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartGarage.MVC.Mapper;
using SmartGarage.Services.Contracts;
using SmartGarage.Services.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartGarage.MVC.Controllers
{
    public class VisitController : Controller
    {
        private readonly ICarService carService;
        private readonly IUserService userService;
        private readonly IVisitService visitService;
        private readonly IOperationService operationService;
        
        private readonly ViewModelMapper mapper;

        public VisitController(IOperationService operationService, ICarService carService, IUserService userService, IVisitService visitService, ViewModelMapper mapper)
        {
            this.operationService = operationService;
            this.carService = carService;
            this.userService = userService;
            this.visitService = visitService;
            this.mapper = mapper;
        }

        // GET: VisitController
        public async Task<ActionResult> Index(int id, string carId, string beforeDate, string afterDate)
        {
            var cars = await carService.GetAllCarsForUser(id);

            ViewData["CarId"] = new SelectList(cars, "Id", "RegistrationPlate").ToList();

            var OperationFilterDTO = new OperationsFilterDTO();

            if (carId != null && int.TryParse(carId, out int vehId))
                OperationFilterDTO.VehicleId = vehId;
            if (beforeDate != null && DateTime.TryParse(beforeDate, out DateTime beforeD))
                OperationFilterDTO.BeforeDate = beforeD;
            if (afterDate != null && DateTime.TryParse(afterDate, out DateTime afterD))
                OperationFilterDTO.AfterDate = afterD;

            var visits = await this.visitService.GetAllOperationsFiltered(id, OperationFilterDTO);

            var visitVMs = visits.Select(v => mapper.VisitDTOToViewModel(v)).ToList();
            return View(visitVMs);
        }
        
        // GET: VisitController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var visitDTO = await this.visitService.GetVisitAsync(id);

            var visitVM = mapper.VisitDTOToViewModel(visitDTO);

            return View(visitVM);
        }

        // GET: VisitController/Create
        public async Task<ActionResult> Create(int id)
        {
            var cars = await carService.GetAllCarsForUser(id);

            ViewData["CarId"] = new SelectList(cars, "Id", "RegistrationPlate").ToList();

            var ops = await operationService.GetAllOperationsAsync();

            ViewData["OperationId"] = new SelectList(ops, "Id", "Name").ToList();

            return View();
        }

        // POST: VisitController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(int carId, List<int> operationId)
        {
            
            try
            {
                await visitService.CreateAsync(carId, operationId);

                return RedirectToAction("Index","User");
            }
            catch
            {
                return View();
            }
        }
    }
}

SmartGarage/SmartGarage.MVC/Views/Visit/Create.cshtml
@model VisitInputViewModel

<h4>Add new Visit:</h4>

<form asp-area="" asp-controller="Visit" asp-action="Create">
    <div class="form-group custom-size" sstyle="display: initial;">

        <label>Car</label>
        <select name="CarId" class="form-control" asp-items="@((List<SelectListItem>)ViewData["CarId"])"></select>

        <label>Services</label>
        <select name="OperationId" class="select-dropdown form-control" readonly="true" multiple asp-items="@((List<SelectListItem>)ViewData["OperationId"])"></select>

        <br />
        <input type="submit" value="Create" role="button" class="btn btn-primary" />
    </div>
</form>

SmartGarage/SmartGarage.MVC/Views/Visit/Details.cshtml
@model VisitCurrencyViewModel

<div class="row">
    <div class="col-3">
        @Html.DisplayNameFor(x => x.TotalPrice)
    </div>
    <div class="col-8">
        @Model.TotalPrice
        @Model.Currency
    </div>
    <div class="col-3">
        @Html.DisplayNameFor(x => x.Date)
    </div>
    <div class="col-8">
        @Model.Date
    </div>
    <div class="col-3">
        Car
    </div>
    <div class="col-8">
        @Model.CarId
    </div>
    <div class="col-3">
        Operations
    </div>
    <div class="col-8">
        @foreach (var i in Model.Operations)
        {

            <td>
                @i.Name <br>
            </td>
            <td>
                @i.PriceValue
                @i.PriceCurrency <br>
            </td>

        }
    </div>
</div>
<hr />
<div>
    <a class="btn btn-info" onclick="window.history.back()">Go back</a>
</div>

SmartGarage/SmartGarage.MVC/Views/Visit/Index.cshtml
@model IEnumerable<VisitCurrencyViewModel>

<form asp-area="" asp-controller="Visit" asp-action="Index">
    <div class="form-group custom-size">

        <label>Car</label>
        <select name="CarId" class="form-control" asp-items="@((List<SelectListItem>)ViewData["CarId"])"></select>

        <label>BeforeDate</label>
        <input name="BeforeDate" type="date" class="form-control" id="BeforeDate">

        <label>AfterDate</label>
        <input name="AfterDate" type="date" class="form-control" id="AfterDate">

        <br />
        <input type="submit" value="Search" role="button" class="btn btn-primary" />
    </div>
</form>

<table class="table">
    <thead class="thead-light">
        <tr>
            <th>Visits</th>
            <th>Car</th>
            <th>Date</th>
            <th>Service Name</th>
            <th>Price</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model)
        {
            <tr>
                <th scope="row">@i.Id</th>
                <td>@i.CarId</td>
                <td>@i.Date</td>
                <td>
                    @foreach (var p in i.Operations)
                    {
                        <p>
                            @p.Name
                        </p>
                    }
                </td>
                <td>
                    @foreach (var p in i.Operations)
                    {
                        <p>
                            @p.PriceValue @p.PriceCurrency
                        </p>

                    }
                </td>
                <td><a asp-action="Details" asp-route-id="@i.Id" class="btn btn-info">Details</a></td>

            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-controller="User" asp-action="Index" class="btn btn-info">Back to Index</a>
</div>